@startuml

package "sledge-core" as core {
	interface PackageRepository
	interface DeploymentConfiguration
	interface PackageSourceConnector
	interface Installer
	interface ApplicationPackageExtractor
	class ApplicationPackage
	class SledgeInstallServlet
	class SledgeUninstallServlet
	class SledgeUploadServlet
	class SledgeConfigServlet
}

hide members

@enduml