@startuml
left to right direction
skinparam packageStyle rect
actor admin <<User>>
actor "External system" as extSystem <<System>>
rectangle "Sledge" {
  admin -- (checkout)
  (checkout) .> (payment) : include
  (help) .> (checkout) : extends
  (checkout) -- extSystem
}
@enduml